{
 "title": "Linux OS Overview",
 "tags": [ "IBM APM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "os", "label": "Linux OS Agent Instance", "query": "label_values(originnode)" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "itm_msys_available{originnode=\"$os\"}"
    }
   ]
  },
  {
   "title": "Current CPU BUSY %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "itm_klzcpu_busycpu{originnode=\"$os\"}",
     "legendFormat": "cpuid: {{ cpuid }}"
    }
   ]
  },
  {
   "title": "CPU - BUSY CPU %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "itm_klzcpu_busycpu{originnode=\"$os\"}",
     "legendFormat": "cpuid: {{ cpuid }}"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "itm_klzdisk_dskusedpct{originnode=\"$os\"} > 0",
     "legendFormat": "{{ mountpt }}"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "itm_klzdisk_dskusedpct{originnode=\"$os\"} > 0"
    }
   ]
  },
  {
   "title": "Transfered bytes per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "itm_klznet_transbps{originnode=\"$os\"}",
     "legendFormat": "{{ fname }}"
    }
   ]
  },
  {
   "title": "Memory used %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "itm_klzvm_netmemupct{originnode=\"$os\"}"
    }
   ]
  },
  {
   "title": "Memory free %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "itm_klzvm_totmemfpct{originnode=\"$os\"}"
    }
   ]
  }
 ]
}