{
 "title": "Top 10 | Bottom 10 CPU systems & Scrape stats",
 "tags": [ "IBM APM" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Top 10 CPU Busy % Systems",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,avg_over_time(itm_klzcpu_busycpu{cpuid=\"Aggregate\"}[10m]))",
     "legendFormat": "{{ originnode }}"
    }
   ]
  },
  {
   "title": "Bottom 10 CPU Busy % Systems",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "bottomk(10,avg_over_time(itm_klzcpu_busycpu{cpuid=\"Aggregate\"}[10m]))",
     "legendFormat": "{{ originnode }}"
    }
   ]
  },
  {
   "title": "Total scrape duration seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "itm_scrape_duration_seconds" }
   ]
  },
  {
   "title": "Scrape time per Attribute Group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "itm_scrape_duration_seconds", "legendFormat": "{{ group }}" }
   ]
  },
  {
   "title": "Number of Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(itm_msys_available == 1)" }
   ]
  },
  {
   "title": "Number of Online Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(itm_msys_available == 1)" }
   ]
  },
  { "title": "Grafana alert list", "type": "alertlist", "gridPos": { "h": 3, "w": 14, "x": 10, "y": 12 } }
 ]
}